version: "3.8"

volumes:
  n8n_local_data:
  ollama_local_data:


networks:
  n8n-net:


services:
  ollama:
    image: ollama/ollama:latest
    container_name: ${COMPOSE_PROJECT_NAME:-n8n}-local-ollama
    restart: always
    volumes:
      - ollama_local_data:/root/.ollama
    networks:
      - n8n-net

  n8n:
    image: docker.n8n.io/n8nio/n8n:${N8N_VERSION:-latest}
    restart: always
    container_name: ${COMPOSE_PROJECT_NAME:-n8n}-local-app
    ports:
      - "5679:5678"
    environment:
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-Asia/Kolkata}
      - TZ=${TZ:-Asia/Kolkata}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_LISTEN_ADDRESS=0.0.0.0
      - WEBHOOK_URL=http://localhost:5679/
      - DB_TYPE=sqlite
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD:-admin123}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY:-local_insecure_key_do_not_use_in_prod}
    volumes:
      - n8n_local_data:/home/node/.n8n
    networks:
      - n8n-net
    depends_on:
      - ollama
